### ISSUE TITLE
time not implemented on this platform

### ISSUE THREAD

**Issue by ErikXu** [proxy-wasm/proxy-wasm-rust-sdk#110]
I encountered the `time not implemented on this platform` issue when integrating the wasm into envoy as a filter. Is there any good idea to get the `utc now` in `wasm32-unknown-unknown` platform in envoy but not browser.

Here is my code:

```
use chrono::Utc;

pub fn unix_timestamp() -> i64 {
    let now = Utc::now();
    now.timestamp()
}

#[test]
fn time_test() {
    use chrono::TimeZone;

    println!("{}", unix_timestamp());
    let d = Utc.timestamp(1614842534, 0);
    println!("{}", d.to_string());
}
```

And the error information:

```
2021-06-23T11:12:20.673222Z	info	Envoy proxy is ready
2021-06-23T11:12:32.345624Z	critical	envoy wasm	wasm log: panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:39:9
```

**Comment by PiotrSikora** [comment]
If you want to use `wasm32-unknown-unknown` target, then you need to use `proxy_wasm::hostcalls::get_current_time()`:
https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/c94f6e4e822d34b5d898e5f078079165805c12fa/examples/hello_world.rs#L45

However, I'd recommend using `wasm32-wasi` target instead, since then you can use the standard Rust APIs:
https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/c94f6e4e822d34b5d898e5f078079165805c12fa/examples/hello_world.rs#L49

**Comment by ErikXu** [comment]
I really appreciate your help. It works perfect now.
