### ISSUE TITLE
Setting gRPC status in http response

### ISSUE THREAD

**Issue by wagenet** [proxy-wasm/proxy-wasm-rust-sdk#148]
Is this possible? It looks like the underlying interface may support it, but it doesn’t seem to be public.

**Comment by juanmolle** [comment]
Do we need to expose? maybe instead of return -1 https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/master/src/hostcalls.rs#L721 we can map http code to the closest grpc code

**Comment by juanmolle** [comment]
@PiotrSikora let us know what you think about this please

**Comment by PiotrSikora** [comment]
This should be fixed in #248.

Note that Envoy doesn't support sending gRPC messages using `sendLocalReply()` calls, and it automatically changes HTTP responses to gRPC errors when talking with gRPC clients, so this is limited to emitting gRPC error responses, and not for producing valid gRPC responses.
