### ISSUE TITLE
Response Buffer Question

### ISSUE THREAD

**Issue by RichiCoder1** [proxy-wasm/proxy-wasm-rust-sdk#37]
Howdy! I wanted to poke at writing a simple html rewriter filter, using https://github.com/cloudflare/lol-html. Looking at the ABI, is the response buffer that one'd be reading from and writing to the same? Aka, if I'm reading body chunks, feeding them into the rewriter, and then writing out chunks am I potentially overwriting the buffer itself and breaking things? Would I need to have an in-wasm buffer to store the transformed body until it's complete and then write that out?

**Comment by gbrail** [comment]
Every time on_http_request_body (or get_response_body) is called, you can
read the body into an Option<Vec<u8>> using get_http_request_body (or
response_body). This gives you a copy of the body chunk that you can
manipulate using Rust.

To update what gets sent to the next filter,  you need to call
set_http_request_body (or response_body) with whatever you want the new
model to be. You can actually replace the entire body chunk, or insert
things in the middle, or even clear it out, depending on what you pass to
the "start" and "size" parameters.

The "http_body" example in the examples directory shows a filter that
optionally replaces the whole body. It does this by returning "Pause"
because it is demonstrating how to let Envoy buffer all the data and give
it to our filter all in one chunk. Since it sounds like your library can
modify HTML in a streaming fashion (which is cool and also unusual) you
don't need that bit -- you should, in theory, be able to read each chunk as
it comes in, pass it to the library, and write out whatever it gives you
back.

**Comment by RichiCoder1** [comment]
Thanks! I'm hoping to give that a try soon to validate an idea. Will post back if I run into any issues.
