### ISSUE TITLE
Issue in the definition of `MapType`

### ISSUE THREAD

**Issue by yskopets** [proxy-wasm/proxy-wasm-rust-sdk#5]
## Summary

* enum values `HttpCallResponseHeaders` and `HttpCallResponseTrailers` have different `int` values than in Envoy

**Comment by PiotrSikora** [comment]
Actually, they match the values that we shipped in Istio 1.5, which froze the `0.1.0` version of the Proxy-Wasm ABI that Rust SDK is implementing:
https://github.com/istio/envoy/blob/release-1.5/api/wasm/cpp/proxy_wasm_common.h#L65-L66

Unfortunately, it seems that we've changed it in the versions of Envoy that we shipped in Istio 1.6 and Istio 1.7:
https://github.com/istio/envoy/blob/release-1.6/api/wasm/cpp/proxy_wasm_common.h#L64-L65
https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/master/proxy_wasm_common.h#L84-L85
but since they also advertise `0.1.0` version of the Proxy-Wasm ABI, I'm not sure if there is a good way to solve this.

The next version of the Proxy-Wasm ABI should be around the corner, so it will get sorted out then.

**Comment by PiotrSikora** [comment]
I've been reviewing the state of the ABI compatibility, and it seems that we've ended up in an unfixable position across Istio versions, and we might need to break the Istio 1.5 compatibility after all.

**Comment by PiotrSikora** [comment]
OK, the plan of record is that we're going to abandon Istio 1.5 compatibility.

Unfortunately, there was an incompatible change (https://github.com/envoyproxy/envoy-wasm/pull/461) introduced to the Proxy-Wasm ABI that shipped in Istio 1.6. That change applied only to gRPC callouts, which neither AssemblyScript, nor Rust, nor TinyGo SDKs implement, but it included the problematic renumbering of the `HeaderMapType` values, which is impossible to detect at runtime in SDKs that don't implement gRPC callouts, so we can only support either Istio 1.5 or Istio 1.6 variant of the Proxy-Wasm ABI version 0.1.0.

As such, the decision has been made update Proxy-Wasm ABI version 0.1.0 to match what shipped in Istio 1.6.

On a side note, I've added support for multiple ABI versions to Envoy, so SDKs implementing this version should be working in Istio 1.6, Istio 1.7, Envoy-Wasm (master), and future releases for the foreseeable future.

**Comment by PiotrSikora** [comment]
For the reference:
[v0.1.0] and [v0.1.1] work with Istio 1.5,
[v0.1.2] and future releases work with Istio 1.6, Istio 1.7 and Envoy-Wasm (master).

[v0.1.0]: https://github.com/proxy-wasm/proxy-wasm-rust-sdk/releases/tag/v0.1.0
[v0.1.1]: https://github.com/proxy-wasm/proxy-wasm-rust-sdk/releases/tag/v0.1.1
[v0.1.2]: https://github.com/proxy-wasm/proxy-wasm-rust-sdk/releases/tag/v0.1.2
