### ISSUE TITLE
[Question] Resume on TCP operation after HTTP call?

### ISSUE THREAD

**Issue by MikeSchlosser16** [proxy-wasm/proxy-wasm-rust-sdk#80]
I'm working on a Network filter that sometimes needs to make an HTTP call. I have the HTTP call working using code
```
       match self.dispatch_http_call()
       ...
       return Action::Pause;
``` 

I can then get the response using
```
 fn on_http_call_response(&mut self, token_id: u32,_num_headers: usize, body_size: usize,_num_trailers: usize) {
```  

My issue comes in when I need to resume the filter after the completion of the HTTP call. The TCP connection never gets any more data with results in Envoy never sending more data and I am never able to get back into 
```
    fn on_upstream_data(&mut self, data_size: usize, _end_of_stream: bool) -> Action {
```

It is my understanding we could in theory call a `resume` for a L4 filter similar to

 ```
 pub fn resume_http_response() -> Result<(), Status> {`
```

My questions:
1. Is it still the case that that resume is not implemented? I don't see anything here, and per [this example](https://github.com/tetratelabs/envoy-wasm-rust-sdk/tree/master/examples/network-filter#known-issues) (but realize that hasn't been updated in a while).
2. If (1) is accurate, is there any plans to implement? It appears that it may be missing in envoy per [this issue](https://github.com/tetratelabs/envoy-wasm-rust-sdk/issues/17). 

Any insight here would be super appreciated! Thanks in advance!

**Comment by PiotrSikora** [comment]
Actually, `resume_downstream` and `resume_upstream` are already implemented in the Rust SDK, see: https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/64 (that PR isn't merged yet, because I want to make one more change in 0.1.x before merging breaking changes in that PR).

But as you noted, this feature is also missing in Envoy. I have it implemented already, but I still need to add tests. Hopefully, I should be able to open a PR early next week.

**Comment by MikeSchlosser16** [comment]
Thanks @PiotrSikora - really appreciate your work here!

**Comment by PiotrSikora** [comment]
PR in Envoy: https://github.com/envoyproxy/envoy/pull/15393. Sorry for the delay!
